//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ServiceReferenceEmployee {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8834/tsi1/", ConfigurationName="ServiceReferenceEmployee.IServiceEmployees")]
    public interface IServiceEmployees {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/AddEmployee", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/AddEmployeeResponse")]
        void AddEmployee(Web.ServiceReferenceEmployee.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/AddEmployee", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/AddEmployeeResponse")]
        System.Threading.Tasks.Task AddEmployeeAsync(Web.ServiceReferenceEmployee.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/DeleteEmployee", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/DeleteEmployeeResponse")]
        void DeleteEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/DeleteEmployee", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/UpdateEmployee", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/UpdateEmployeeResponse")]
        void UpdateEmployee(Web.ServiceReferenceEmployee.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/UpdateEmployee", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/UpdateEmployeeResponse")]
        System.Threading.Tasks.Task UpdateEmployeeAsync(Web.ServiceReferenceEmployee.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/GetAllEmployees", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/GetAllEmployeesResponse")]
        Web.ServiceReferenceEmployee.Employee[] GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/GetAllEmployees", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/GetAllEmployeesResponse")]
        System.Threading.Tasks.Task<Web.ServiceReferenceEmployee.Employee[]> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/GetEmployee", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/GetEmployeeResponse")]
        Web.ServiceReferenceEmployee.Employee GetEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/GetEmployee", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/GetEmployeeResponse")]
        System.Threading.Tasks.Task<Web.ServiceReferenceEmployee.Employee> GetEmployeeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/CalcPartTimeEmployeeSalary", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/CalcPartTimeEmployeeSalaryResponse")]
        double CalcPartTimeEmployeeSalary(int idEmployee, int hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8834/tsi1/IServiceEmployees/CalcPartTimeEmployeeSalary", ReplyAction="http://localhost:8834/tsi1/IServiceEmployees/CalcPartTimeEmployeeSalaryResponse")]
        System.Threading.Tasks.Task<double> CalcPartTimeEmployeeSalaryAsync(int idEmployee, int hours);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEmployeesChannel : Web.ServiceReferenceEmployee.IServiceEmployees, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEmployeesClient : System.ServiceModel.ClientBase<Web.ServiceReferenceEmployee.IServiceEmployees>, Web.ServiceReferenceEmployee.IServiceEmployees {
        
        public ServiceEmployeesClient() {
        }
        
        public ServiceEmployeesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEmployeesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmployeesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmployeesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddEmployee(Web.ServiceReferenceEmployee.Employee emp) {
            base.Channel.AddEmployee(emp);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(Web.ServiceReferenceEmployee.Employee emp) {
            return base.Channel.AddEmployeeAsync(emp);
        }
        
        public void DeleteEmployee(int id) {
            base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(int id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public void UpdateEmployee(Web.ServiceReferenceEmployee.Employee emp) {
            base.Channel.UpdateEmployee(emp);
        }
        
        public System.Threading.Tasks.Task UpdateEmployeeAsync(Web.ServiceReferenceEmployee.Employee emp) {
            return base.Channel.UpdateEmployeeAsync(emp);
        }
        
        public Web.ServiceReferenceEmployee.Employee[] GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReferenceEmployee.Employee[]> GetAllEmployeesAsync() {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public Web.ServiceReferenceEmployee.Employee GetEmployee(int id) {
            return base.Channel.GetEmployee(id);
        }
        
        public System.Threading.Tasks.Task<Web.ServiceReferenceEmployee.Employee> GetEmployeeAsync(int id) {
            return base.Channel.GetEmployeeAsync(id);
        }
        
        public double CalcPartTimeEmployeeSalary(int idEmployee, int hours) {
            return base.Channel.CalcPartTimeEmployeeSalary(idEmployee, hours);
        }
        
        public System.Threading.Tasks.Task<double> CalcPartTimeEmployeeSalaryAsync(int idEmployee, int hours) {
            return base.Channel.CalcPartTimeEmployeeSalaryAsync(idEmployee, hours);
        }
    }
}
